name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - matplotlib=3.5.1=py39haa95532_1
  - matplotlib-base=3.5.1=py39hd77b12b_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - numpy=1.21.5=py39h7a0a035_1
  - numpy-base=1.21.5=py39hca35cd5_1
  - numpydoc=1.2=pyhd3eb1b0_0
  - pandas=1.4.2=py39hd77b12b_0
  - seaborn=0.11.2=pyhd3eb1b0_0

